import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRef } from 'react'
import DownloadButton from '../components/DownloadButton'
import Receipt from '../components/Receipt'

const Home: NextPage = () => {

  return (
    <div className="antialiased">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-screen-xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <section
          className="flex items-center justify-center mb-4"
        >
          <Receipt></Receipt>
        </section>
        {/* <DownloadButton dom={receipt.current}></DownloadButton> */}
      </div>
    </div>
  )
}

export default Home
