import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Modal from '../components/Modal'
import Navigation from '../components/Navigation'
import Receipt from '../components/Receipt'
import useEns from '../hooks/useEns'
import useNfts from '../hooks/useNfts'
import useWallet from '../hooks/useWallet'

const Home: NextPage = () => {
  const { address, connect, disconnect } = useWallet()
  const { ens } = useEns(address || '')
  const [isModalOpen, setIsModalOpen] = useState(false)

  const { nfts, total, loading } = useNfts(address || '')

  useEffect(() => {
    if (nfts.length > 0) {
      console.log('useEffect')
      const interval = setInterval(() => {
        console.log('setInterval')
        setIsModalOpen(true)
        clearInterval(interval)
      }, 5000)
    }
  }, [nfts])

  return (
    <div className="antialiased overflow-hidden relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-800 h-screen font-sans">
        <div className="max-w-screen-xl mx-auto px-4 sm:px-6 lg:px-8 py-16 ">
          {!loading && nfts.length === 0 && (
            <h1 className="mb-4 text-center leading-relaxed font-bold text-2xl text-white max-w-2xl mx-auto">
              Generate your NFT 2022 Receipt and send to your tax accountant
            </h1>
          )}
          {loading && (
            <div className="text-white flex flex-col md:flex-row items-center justify-center gap-8 text-center text-2xl">
              Brb...Sorting out your degen stuff
              <div className="dot-elastic"></div>
            </div>
          )}
        </div>

        {address && !loading && (
          <div
            className="flex items-center justify-center cursor-pointer"
            onClick={() => setIsModalOpen(true)}
          >
            <Receipt
              address={address}
              nfts={nfts}
              total={total}
              ens={ens || ''}
              animated
            ></Receipt>
          </div>
        )}

        {isModalOpen && (
          <Modal onClose={() => setIsModalOpen(false)} total={total}>
            {address && !loading && (
              <Receipt
                address={address}
                nfts={nfts}
                total={total}
                ens={ens || ''}
              ></Receipt>
            )}
          </Modal>
        )}

        {/* <button
          onClick={() => {
            setIsModalOpen(true)
          }}
          className="text-white"
        >
          Open
        </button> */}
        <Navigation
          address={address || ''}
          connect={connect}
          disconnect={disconnect}
        ></Navigation>
      </div>
    </div>
  )
}

export default Home
