import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import Computer from '../components/Computer'
import useNfts from '../hooks/useNfts'
import useWallet from '../hooks/useWallet'

const Home: NextPage = () => {
  const { address, connect, disconnect } = useWallet()

  const { nfts, total, loading } = useNfts(address || '')

  useEffect(() => {
    if (!address) return
  }, [address])

  return (
    <div className="antialiased">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-screen-xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <section className="flex flex-col items-center justify-center mb-4">
          <h1 className="mb-4 font-bold ">NFT Receipt Generator</h1>
          <Computer></Computer>
        </section>
      </div>
    </div>
  )
}

export default Home
